---# Install http server and Deploy the Html File
- hosts: master
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Install httpd Server
    yum:
      name: httpd
      state: present
    notify:
     - startservice
  handlers:
  - name: startservice
    service:
      name: httpd
      state: restarted
      enabled: yes
